trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: 'LTS'
      checkLatest: true
      packageType: tool

  - script: |
      cd /home/site/wwwroot
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd /home/site/wwwroot
      npm run build
    displayName: 'Build'
