# For more information: https://laravel.com/docs/sail
version: '3'
services:
    hris:
        container_name: hris.app
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: joowdx/sail:8.2
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        ports:
            - 8000:8000
        networks:
            - sail
        depends_on:
            - mysql
    nginx:
        container_name: hris.webserver
        image: 'nginx:alpine'
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - '.:/usr/share/nginx/html'
            - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
            - './docker/private:/etc/ssl/private:ro'
        networks:
            - 'sail'
        depends_on:
            - 'hris'
        healthcheck:
            test: ["CMD", "wget -O /dev/null http://localhost || exit 1"]
            timeout: 10s
    mysql:
        container_name: hris.database
        image: 'mysql:8-debian'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    mysql:
        name: hris-mysql
        driver: local
